spring:
  datasource:
    url: jdbc:h2:file:./data/testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false
      path: /h2-console

token:
telegram:
  proxy:
    enabled: true
    host: t.bifit.com
    port: 49910
    user: t_users
    password:

server:
  port: 8081